site_title: Harder Sound
site_logo: /img/logo.png
site_email: harder-sound@sympatico.ca
site_tel: (514)-501-0169
site_description: >-
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sit amet
  iaculis elit. Nam semper ut arcu non placerat. Praesent nibh massa varius.
url_facebook: 'https://facebook.com'
url_soundcloud: 'https://soundcloud.com'
