backend:

  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "img"

collections:

  - name: "pages"
    label: "Pages"
    delete: false # Prevent users from deleting documents in this collection
    files:
      - name: "home"
        file: "index.md"
        label: "Edit the home page"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/" }
          - {label: "Description (Google)", name: "description", widget: "string"}
          - {label: "Cover Image", name: "cover_image", widget: "image"}
          - {label: "Cover Text 1", name: "cover_text_1", widget: "string"}
          - {label: "Cover Text 2", name: "cover_text_2", widget: "string"}
          - {label: "Intro Title", name: "intro_title", widget: "string"}
          - {label: "Intro Text 1", name: "intro_1", widget: "markdown"}
          - {label: "Intro Text 2", name: "intro_2", widget: "markdown"}
          - label: "Services"
            name: "services"
            widget: "list"
            fields:
              - {label: Icon, name: service_icon, widget: string }
              - {label: Titre, name: service_title, widget: string }
          - label: "Client Category"
            name: "clients"
            widget: "list"
            fields:
              - {label: Client Category Title, name: client_title, widget: string }
              - label: "Client"
                name: "client_list"
                widget: "list"
                fields:
                  - {label: Name, name: name, widget: string }

      - name: "music"
        file: "music.md"
        label: "Edit the Music page"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/music" }
          - {label: "Description (Google)", name: "description", widget: "string"}
          - {label: "Content", name: "content", widget: "markdown", required: false}
          - label: "Music"
            name: "music"
            widget: "list"
            fields:
              - {label: SoundCloud Embed Code, name: soundcloud, widget: string }

      - name: "gallery"
        file: "gallery.md"
        label: "Edit the Gallery page"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "gallery"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/gallery" }
          - {label: "Description (Google)", name: "description", widget: "string"}
          - {label: "Content", name: "content", widget: "markdown", required: false}
          - label: "Gallery"
            name: "gallery"
            widget: "list"
            fields:
              - {label: Name, name: name, widget: string }
              - {label: Description, name: desc, widget: string }
              - {label: Image, name: image, widget: image }

      - name: "contact"
        file: "contact.md"
        label: "Edit the Contact page"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "contact"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/contact" }
          - {label: "Description (Google)", name: "description", widget: "string"}
          - {label: "Content", name: "content", widget: "markdown", required: false}

  - name: "settings"
    label: "Paramètres du site"
    delete: false # Prevent users from deleting documents in this collection
    editor:
     preview: false
    files:
       - name: "general"
         label: "Général"
         file: "_data/settings.yml"
         description: "Paramètres Généraux"
         fields:
           - {label: "Website Title", name: "site_title", widget: "string"}
           - {label: "Website Logo (optional)", name: "site_logo", widget: "image", required: false}
           - {label: "Contact email", name: "site_email", widget: "string", required: false}
           - {label: "Phone Number", name: "site_tel", widget: "string", required: false}
           - {label: "Facebook", name: "url_facebook", widget: "string", required: false}
           - {label: "Soundcloud", name: "url_soundcloud", widget: "string", required: false}
           - {label: "Instagram", name: "url_instagram", widget: "string", required: false}
           - {label: "Twitter", name: "url_twitter", widget: "string", required: false}
           - {label: "Linked In", name: "url_linkedin", widget: "string", required: false}
